# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

# build html
# jupyter-book build stat-arb-book/
# build pdf
# jupyter-book build stat-arb-book/ --builder pdfhtml


title: "Beyond the Numbers: A Trader's Guide to Statistical Arbitrage and Convex Optimization"
author: Kris Longmore
logo: logo.png
copyright: "2024"

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: 'off'

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Information about where the book exists on the web
repository:
  url: https://github.com/executablebooks/jupyter-book  # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  extra_footer: |
        <div>
            <a href="https://robotwealth.com">robotwealth.com</a>
        </div>

    
